#!/bin/bash

PKG_NAME="openSeaChest"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"

source /pkgscripts/include/pkg_util.sh

PrepareDirs() {
    for dir in $INST_DIR $PKG_DIR; do
        rm -rf "$dir"
    done
    for dir in $INST_DIR $PKG_DIR $PKG_DEST; do
        mkdir -p "$dir"
    done
}

MakePackage() {
    cp -r package/* "${INST_DIR}"

    pkg_make_package $INST_DIR $PKG_DIR
}

MakeSpk() {
    cp -r conf "${PKG_DIR}"
    cp PACKAGE_ICON{,_256}.PNG "${PKG_DIR}"
    cp -r scripts "${PKG_DIR}"

    ./INFO.sh > INFO
    cp INFO "${PKG_DIR}"

    pkg_make_spk $PKG_DIR $PKG_DEST $(pkg_get_spk_family_name)
}

main() {
    PrepareDirs
    MakePackage
    MakeSpk
}

main "$@"